<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class ThemeSettings {
	private $theme_settings_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'theme_settings_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'theme_settings_page_init' ) );
	}

	public function theme_settings_add_plugin_page() {
		add_menu_page(
			'Theme Settings', // page_title
			'Theme Settings', // menu_title
			'manage_options', // capability
			'theme-settings', // menu_slug
			array( $this, 'theme_settings_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			2 // position
		);
	}

	public function theme_settings_create_admin_page() {
		$this->theme_settings_options = get_option( 'theme_settings_option_name' ); ?>

		<div class="wrap">
			<h2>Theme Settings</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'theme_settings_option_group' );
					do_settings_sections( 'theme-settings-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function theme_settings_page_init() {
		register_setting(
			'theme_settings_option_group', // option_group
			'theme_settings_option_name', // option_name
			array( $this, 'theme_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'theme_settings_setting_section', // id
			'Settings', // title
			array( $this, 'theme_settings_section_info' ), // callback
			'theme-settings-admin' // page
		);

		add_settings_field(
			'tiktok_0', // id
			'TikTok', // title
			array( $this, 'tiktok_0_callback' ), // callback
			'theme-settings-admin', // page
			'theme_settings_setting_section' // section
		);

		add_settings_field(
			'instagram_1', // id
			'Instagram', // title
			array( $this, 'instagram_1_callback' ), // callback
			'theme-settings-admin', // page
			'theme_settings_setting_section' // section
		);

		add_settings_field(
			'facebook_2', // id
			'Facebook', // title
			array( $this, 'facebook_2_callback' ), // callback
			'theme-settings-admin', // page
			'theme_settings_setting_section' // section
		);

		add_settings_field(
			'youtube_3', // id
			'Youtube', // title
			array( $this, 'youtube_3_callback' ), // callback
			'theme-settings-admin', // page
			'theme_settings_setting_section' // section
		);
	}

	public function theme_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['tiktok_0'] ) ) {
			$sanitary_values['tiktok_0'] = sanitize_text_field( $input['tiktok_0'] );
		}

		if ( isset( $input['instagram_1'] ) ) {
			$sanitary_values['instagram_1'] = sanitize_text_field( $input['instagram_1'] );
		}

		if ( isset( $input['facebook_2'] ) ) {
			$sanitary_values['facebook_2'] = sanitize_text_field( $input['facebook_2'] );
		}

		if ( isset( $input['youtube_3'] ) ) {
			$sanitary_values['youtube_3'] = sanitize_text_field( $input['youtube_3'] );
		}

		return $sanitary_values;
	}

	public function theme_settings_section_info() {
		
	}

	public function tiktok_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_settings_option_name[tiktok_0]" id="tiktok_0" value="%s">',
			isset( $this->theme_settings_options['tiktok_0'] ) ? esc_attr( $this->theme_settings_options['tiktok_0']) : ''
		);
	}

	public function instagram_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_settings_option_name[instagram_1]" id="instagram_1" value="%s">',
			isset( $this->theme_settings_options['instagram_1'] ) ? esc_attr( $this->theme_settings_options['instagram_1']) : ''
		);
	}

	public function facebook_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_settings_option_name[facebook_2]" id="facebook_2" value="%s">',
			isset( $this->theme_settings_options['facebook_2'] ) ? esc_attr( $this->theme_settings_options['facebook_2']) : ''
		);
	}

	public function youtube_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="theme_settings_option_name[youtube_3]" id="youtube_3" value="%s">',
			isset( $this->theme_settings_options['youtube_3'] ) ? esc_attr( $this->theme_settings_options['youtube_3']) : ''
		);
	}

}
if ( is_admin() )
	$theme_settings = new ThemeSettings();

/* 
 * Retrieve this value with:
 * $theme_settings_options = get_option( 'theme_settings_option_name' ); // Array of All Options
 * $tiktok_0 = $theme_settings_options['tiktok_0']; // TikTok
 * $instagram_1 = $theme_settings_options['instagram_1']; // Instagram
 * $facebook_2 = $theme_settings_options['facebook_2']; // Facebook
 * $youtube_3 = $theme_settings_options['youtube_3']; // Youtube
 */
